name: CityWorld
main: me.daddychurchill.CityWorld.CityWorld
version: 0.52
load: startup
author: DaddyChurchill
commands:
  cityworld:
    description: Sends you to the cityworld.
    usage: /cityworld
  cityworlddebug:
    description: Does something, still not sure what though.
    usage: /cityworlddebug
    