name: CityWorld
main: me.daddychurchill.CityWorld.CityWorld
version: 1.00
load: startup
author: DaddyChurchill
commands:
  cityworld:
    description: Sends you to the CityWorld
    usage: /cityworld
    