name: CityWorld
main: me.daddychurchill.CityWorld.CityWorld
version: 0.57
load: startup
author: DaddyChurchill
commands:
  cityworld:
    description: Sends you to the cityworld.
    usage: /cityworld
    