name: CityWorld
main: me.daddychurchill.CityWorld.CityWorld
version: 1.06
load: startup
author: DaddyChurchill
commands:
  cityworld:
    description: Teleports you to/from the default CityWorld
    usage: /cityworld [leave]
  citychunk:
    description: Performs specific maintenance on chunks of CityWorld
    usage: /citychunk regen | clean [chunkradius]
    